package com.acmatics.securityguardexchange.dao;

import com.acmatics.securityguardexchange.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANSWER_CHOICE".
 */
public class AnswerChoice {

    private Long answerChoiceId;
    private String textKey;
    private Long questionId;
    private Boolean isAnswerFlag;
    private Boolean imageFlag;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AnswerChoiceDao myDao;

    private Question question;
    private Long question__resolvedKey;


    public AnswerChoice() {
    }

    public AnswerChoice(Long answerChoiceId) {
        this.answerChoiceId = answerChoiceId;
    }

    public AnswerChoice(Long answerChoiceId, String textKey, Long questionId, Boolean isAnswerFlag, Boolean imageFlag) {
        this.answerChoiceId = answerChoiceId;
        this.textKey = textKey;
        this.questionId = questionId;
        this.isAnswerFlag = isAnswerFlag;
        this.imageFlag = imageFlag;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAnswerChoiceDao() : null;
    }

    public Long getAnswerChoiceId() {
        return answerChoiceId;
    }

    public void setAnswerChoiceId(Long answerChoiceId) {
        this.answerChoiceId = answerChoiceId;
    }

    public String getTextKey() {
        return textKey;
    }

    public void setTextKey(String textKey) {
        this.textKey = textKey;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public Boolean getIsAnswerFlag() {
        return isAnswerFlag;
    }

    public void setIsAnswerFlag(Boolean isAnswerFlag) {
        this.isAnswerFlag = isAnswerFlag;
    }

    public Boolean getImageFlag() {
        return imageFlag;
    }

    public void setImageFlag(Boolean imageFlag) {
        this.imageFlag = imageFlag;
    }

    /** To-one relationship, resolved on first access. */
    public Question getQuestion() {
        Long __key = this.questionId;
        if (question__resolvedKey == null || !question__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            QuestionDao targetDao = daoSession.getQuestionDao();
            Question questionNew = targetDao.load(__key);
            synchronized (this) {
                question = questionNew;
            	question__resolvedKey = __key;
            }
        }
        return question;
    }

    public void setQuestion(Question question) {
        synchronized (this) {
            this.question = question;
            questionId = question == null ? null : question.getQuestionId();
            question__resolvedKey = questionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
