package com.acmatics.securityguardexchange.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.acmatics.securityguardexchange.dao.AnswerChoice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER_CHOICE".
*/
public class AnswerChoiceDao extends AbstractDao<AnswerChoice, Long> {

    public static final String TABLENAME = "ANSWER_CHOICE";

    /**
     * Properties of entity AnswerChoice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AnswerChoiceId = new Property(0, Long.class, "answerChoiceId", true, "ANSWER_CHOICE_ID");
        public final static Property TextKey = new Property(1, String.class, "textKey", false, "TEXT_KEY");
        public final static Property QuestionId = new Property(2, Long.class, "questionId", false, "QUESTION_ID");
        public final static Property IsAnswerFlag = new Property(3, Boolean.class, "isAnswerFlag", false, "IS_ANSWER_FLAG");
        public final static Property ImageFlag = new Property(4, Boolean.class, "imageFlag", false, "IMAGE_FLAG");
    };

    private DaoSession daoSession;

    private Query<AnswerChoice> question_AnswerChoicesQuery;

    public AnswerChoiceDao(DaoConfig config) {
        super(config);
    }
    
    public AnswerChoiceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER_CHOICE\" (" + //
                "\"ANSWER_CHOICE_ID\" INTEGER PRIMARY KEY ," + // 0: answerChoiceId
                "\"TEXT_KEY\" TEXT," + // 1: textKey
                "\"QUESTION_ID\" INTEGER," + // 2: questionId
                "\"IS_ANSWER_FLAG\" INTEGER," + // 3: isAnswerFlag
                "\"IMAGE_FLAG\" INTEGER);"); // 4: imageFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER_CHOICE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AnswerChoice entity) {
        stmt.clearBindings();
 
        Long answerChoiceId = entity.getAnswerChoiceId();
        if (answerChoiceId != null) {
            stmt.bindLong(1, answerChoiceId);
        }
 
        String textKey = entity.getTextKey();
        if (textKey != null) {
            stmt.bindString(2, textKey);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(3, questionId);
        }
 
        Boolean isAnswerFlag = entity.getIsAnswerFlag();
        if (isAnswerFlag != null) {
            stmt.bindLong(4, isAnswerFlag ? 1L: 0L);
        }
 
        Boolean imageFlag = entity.getImageFlag();
        if (imageFlag != null) {
            stmt.bindLong(5, imageFlag ? 1L: 0L);
        }
    }

    @Override
    protected void attachEntity(AnswerChoice entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AnswerChoice readEntity(Cursor cursor, int offset) {
        AnswerChoice entity = new AnswerChoice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // answerChoiceId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // textKey
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // questionId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isAnswerFlag
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // imageFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AnswerChoice entity, int offset) {
        entity.setAnswerChoiceId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTextKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setQuestionId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsAnswerFlag(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setImageFlag(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AnswerChoice entity, long rowId) {
        entity.setAnswerChoiceId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AnswerChoice entity) {
        if(entity != null) {
            return entity.getAnswerChoiceId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "answerChoices" to-many relationship of Question. */
    public List<AnswerChoice> _queryQuestion_AnswerChoices(Long questionId) {
        synchronized (this) {
            if (question_AnswerChoicesQuery == null) {
                QueryBuilder<AnswerChoice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.QuestionId.eq(null));
                question_AnswerChoicesQuery = queryBuilder.build();
            }
        }
        Query<AnswerChoice> query = question_AnswerChoicesQuery.forCurrentThread();
        query.setParameter(0, questionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getQuestionDao().getAllColumns());
            builder.append(" FROM ANSWER_CHOICE T");
            builder.append(" LEFT JOIN QUESTION T0 ON T.\"QUESTION_ID\"=T0.\"QUESTION_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AnswerChoice loadCurrentDeep(Cursor cursor, boolean lock) {
        AnswerChoice entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Question question = loadCurrentOther(daoSession.getQuestionDao(), cursor, offset);
        entity.setQuestion(question);

        return entity;    
    }

    public AnswerChoice loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AnswerChoice> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AnswerChoice> list = new ArrayList<AnswerChoice>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AnswerChoice> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AnswerChoice> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
