package com.acmatics.securityguardexchange.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.acmatics.securityguardexchange.dao.QuestionLevel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUESTION_LEVEL".
*/
public class QuestionLevelDao extends AbstractDao<QuestionLevel, Long> {

    public static final String TABLENAME = "QUESTION_LEVEL";

    /**
     * Properties of entity QuestionLevel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property QuestionLevelId = new Property(0, Long.class, "questionLevelId", true, "QUESTION_LEVEL_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
    };


    public QuestionLevelDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionLevelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUESTION_LEVEL\" (" + //
                "\"QUESTION_LEVEL_ID\" INTEGER PRIMARY KEY ," + // 0: questionLevelId
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIPTION\" TEXT);"); // 2: description
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUESTION_LEVEL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, QuestionLevel entity) {
        stmt.clearBindings();
 
        Long questionLevelId = entity.getQuestionLevelId();
        if (questionLevelId != null) {
            stmt.bindLong(1, questionLevelId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public QuestionLevel readEntity(Cursor cursor, int offset) {
        QuestionLevel entity = new QuestionLevel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // questionLevelId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // description
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, QuestionLevel entity, int offset) {
        entity.setQuestionLevelId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(QuestionLevel entity, long rowId) {
        entity.setQuestionLevelId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(QuestionLevel entity) {
        if(entity != null) {
            return entity.getQuestionLevelId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
