package com.acmatics.securityguardexchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUESTION_LEVEL".
 */
public class QuestionLevel {

    private Long questionLevelId;
    private String name;
    private String description;

    public QuestionLevel() {
    }

    public QuestionLevel(Long questionLevelId) {
        this.questionLevelId = questionLevelId;
    }

    public QuestionLevel(Long questionLevelId, String name, String description) {
        this.questionLevelId = questionLevelId;
        this.name = name;
        this.description = description;
    }

    public Long getQuestionLevelId() {
        return questionLevelId;
    }

    public void setQuestionLevelId(Long questionLevelId) {
        this.questionLevelId = questionLevelId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
