package com.acmatics.securityguardexchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUESTION_TYPE".
 */
public class QuestionType {

    private Long questionTypeId;
    private String name;
    private String description;

    public QuestionType() {
    }

    public QuestionType(Long questionTypeId) {
        this.questionTypeId = questionTypeId;
    }

    public QuestionType(Long questionTypeId, String name, String description) {
        this.questionTypeId = questionTypeId;
        this.name = name;
        this.description = description;
    }

    public Long getQuestionTypeId() {
        return questionTypeId;
    }

    public void setQuestionTypeId(Long questionTypeId) {
        this.questionTypeId = questionTypeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
