package com.acmatics.securityguardexchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUIZ_TYPE".
 */
public class QuizType {

    private Long quizTypeId;
    private String name;
    private String description;

    public QuizType() {
    }

    public QuizType(Long quizTypeId) {
        this.quizTypeId = quizTypeId;
    }

    public QuizType(Long quizTypeId, String name, String description) {
        this.quizTypeId = quizTypeId;
        this.name = name;
        this.description = description;
    }

    public Long getQuizTypeId() {
        return quizTypeId;
    }

    public void setQuizTypeId(Long quizTypeId) {
        this.quizTypeId = quizTypeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
