package com.acmatics.securityguardexchange.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.acmatics.securityguardexchange.dao.Quiz;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUIZ".
*/
public class QuizDao extends AbstractDao<Quiz, Long> {

    public static final String TABLENAME = "QUIZ";

    /**
     * Properties of entity Quiz.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property QuizId = new Property(0, Long.class, "quizId", true, "QUIZ_ID");
        public final static Property QuizDate = new Property(1, java.util.Date.class, "quizDate", false, "QUIZ_DATE");
        public final static Property QuizTypeId = new Property(2, Long.class, "quizTypeId", false, "QUIZ_TYPE_ID");
        public final static Property QuizName = new Property(3, String.class, "quizName", false, "QUIZ_NAME");
        public final static Property Description = new Property(4, String.class, "description", false, "DESCRIPTION");
        public final static Property MaxDuration = new Property(5, Integer.class, "maxDuration", false, "MAX_DURATION");
        public final static Property QuestionCount = new Property(6, Integer.class, "questionCount", false, "QUESTION_COUNT");
    };

    private DaoSession daoSession;


    public QuizDao(DaoConfig config) {
        super(config);
    }
    
    public QuizDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUIZ\" (" + //
                "\"QUIZ_ID\" INTEGER PRIMARY KEY ," + // 0: quizId
                "\"QUIZ_DATE\" INTEGER," + // 1: quizDate
                "\"QUIZ_TYPE_ID\" INTEGER," + // 2: quizTypeId
                "\"QUIZ_NAME\" TEXT," + // 3: quizName
                "\"DESCRIPTION\" TEXT," + // 4: description
                "\"MAX_DURATION\" INTEGER," + // 5: maxDuration
                "\"QUESTION_COUNT\" INTEGER);"); // 6: questionCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUIZ\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Quiz entity) {
        stmt.clearBindings();
 
        Long quizId = entity.getQuizId();
        if (quizId != null) {
            stmt.bindLong(1, quizId);
        }
 
        java.util.Date quizDate = entity.getQuizDate();
        if (quizDate != null) {
            stmt.bindLong(2, quizDate.getTime());
        }
 
        Long quizTypeId = entity.getQuizTypeId();
        if (quizTypeId != null) {
            stmt.bindLong(3, quizTypeId);
        }
 
        String quizName = entity.getQuizName();
        if (quizName != null) {
            stmt.bindString(4, quizName);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        Integer maxDuration = entity.getMaxDuration();
        if (maxDuration != null) {
            stmt.bindLong(6, maxDuration);
        }
 
        Integer questionCount = entity.getQuestionCount();
        if (questionCount != null) {
            stmt.bindLong(7, questionCount);
        }
    }

    @Override
    protected void attachEntity(Quiz entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Quiz readEntity(Cursor cursor, int offset) {
        Quiz entity = new Quiz( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // quizId
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // quizDate
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // quizTypeId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // quizName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // description
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // maxDuration
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // questionCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Quiz entity, int offset) {
        entity.setQuizId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuizDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setQuizTypeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setQuizName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescription(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMaxDuration(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setQuestionCount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Quiz entity, long rowId) {
        entity.setQuizId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Quiz entity) {
        if(entity != null) {
            return entity.getQuizId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getQuizTypeDao().getAllColumns());
            builder.append(" FROM QUIZ T");
            builder.append(" LEFT JOIN QUIZ_TYPE T0 ON T.\"QUIZ_TYPE_ID\"=T0.\"QUIZ_TYPE_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Quiz loadCurrentDeep(Cursor cursor, boolean lock) {
        Quiz entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        QuizType quizType = loadCurrentOther(daoSession.getQuizTypeDao(), cursor, offset);
        entity.setQuizType(quizType);

        return entity;    
    }

    public Quiz loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Quiz> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Quiz> list = new ArrayList<Quiz>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Quiz> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Quiz> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
