package com.acmatics.securityguardexchange.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.acmatics.securityguardexchange.dao.TestQuestionMapping;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_QUESTION_MAPPING".
*/
public class TestQuestionMappingDao extends AbstractDao<TestQuestionMapping, Long> {

    public static final String TABLENAME = "TEST_QUESTION_MAPPING";

    /**
     * Properties of entity TestQuestionMapping.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TestQuestionMappingId = new Property(0, Long.class, "testQuestionMappingId", true, "TEST_QUESTION_MAPPING_ID");
        public final static Property QuestionId = new Property(1, Long.class, "questionId", false, "QUESTION_ID");
        public final static Property UserTestId = new Property(2, Long.class, "userTestId", false, "USER_TEST_ID");
    };

    private DaoSession daoSession;


    public TestQuestionMappingDao(DaoConfig config) {
        super(config);
    }
    
    public TestQuestionMappingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_QUESTION_MAPPING\" (" + //
                "\"TEST_QUESTION_MAPPING_ID\" INTEGER PRIMARY KEY ," + // 0: testQuestionMappingId
                "\"QUESTION_ID\" INTEGER," + // 1: questionId
                "\"USER_TEST_ID\" INTEGER);"); // 2: userTestId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_QUESTION_MAPPING\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TestQuestionMapping entity) {
        stmt.clearBindings();
 
        Long testQuestionMappingId = entity.getTestQuestionMappingId();
        if (testQuestionMappingId != null) {
            stmt.bindLong(1, testQuestionMappingId);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(2, questionId);
        }
 
        Long userTestId = entity.getUserTestId();
        if (userTestId != null) {
            stmt.bindLong(3, userTestId);
        }
    }

    @Override
    protected void attachEntity(TestQuestionMapping entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TestQuestionMapping readEntity(Cursor cursor, int offset) {
        TestQuestionMapping entity = new TestQuestionMapping( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // testQuestionMappingId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // questionId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // userTestId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TestQuestionMapping entity, int offset) {
        entity.setTestQuestionMappingId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestionId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUserTestId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TestQuestionMapping entity, long rowId) {
        entity.setTestQuestionMappingId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TestQuestionMapping entity) {
        if(entity != null) {
            return entity.getTestQuestionMappingId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getQuestionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserTestDao().getAllColumns());
            builder.append(" FROM TEST_QUESTION_MAPPING T");
            builder.append(" LEFT JOIN QUESTION T0 ON T.\"QUESTION_ID\"=T0.\"QUESTION_ID\"");
            builder.append(" LEFT JOIN USER_TEST T1 ON T.\"USER_TEST_ID\"=T1.\"USER_TEST_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TestQuestionMapping loadCurrentDeep(Cursor cursor, boolean lock) {
        TestQuestionMapping entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Question question = loadCurrentOther(daoSession.getQuestionDao(), cursor, offset);
        entity.setQuestion(question);
        offset += daoSession.getQuestionDao().getAllColumns().length;

        UserTest userTest = loadCurrentOther(daoSession.getUserTestDao(), cursor, offset);
        entity.setUserTest(userTest);

        return entity;    
    }

    public TestQuestionMapping loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TestQuestionMapping> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TestQuestionMapping> list = new ArrayList<TestQuestionMapping>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TestQuestionMapping> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TestQuestionMapping> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
