package com.acmatics.securityguardexchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_TEST".
 */
public class UserTest {

    private Long userTestId;
    private Integer maxDuration;

    public UserTest() {
    }

    public UserTest(Long userTestId) {
        this.userTestId = userTestId;
    }

    public UserTest(Long userTestId, Integer maxDuration) {
        this.userTestId = userTestId;
        this.maxDuration = maxDuration;
    }

    public Long getUserTestId() {
        return userTestId;
    }

    public void setUserTestId(Long userTestId) {
        this.userTestId = userTestId;
    }

    public Integer getMaxDuration() {
        return maxDuration;
    }

    public void setMaxDuration(Integer maxDuration) {
        this.maxDuration = maxDuration;
    }

}
